#!/bin/bash

# نام فایل خروجی
output_file="ipv4_addresses.txt"

# کشورهای مورد نظر
countries=("JP" "IQ" "EG" "AE" "OM")

# پاک کردن فایل خروجی اگر قبلاً وجود داشته باشد
> $output_file

# تابع برای جستجو و ذخیره آدرس‌های IPv4
get_ipv4_addresses() {
    local country_code=$1
    echo "Getting IPv4 addresses for country code: $country_code"
    whois -h whois.cymru.com " -v ${country_code}" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' >> $output_file
}

# جستجو برای هر کشور
for country in "${countries[@]}"; do
    get_ipv4_addresses $country
done

echo "IP addresses have been saved to $output_file"
